site_name: Home Assistant documentation
use_directory_urls: False
repo_url: http://homeassistant.local:8000
repo_name: View updates in realtime
theme:
  name: material
  logo: assets/mkdocs_icon.png
  features:
    - header.autohide
  include_search_page: false
  search_index_only: true
  palette:
    primary: light blue
extra_css:
  - assets/stylesheet.css
nav:
  - Home: index.md
  - Help/FAQ: addons/mkdocs/help.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - toc:
      permalink: "#"
  - plantuml_markdown:
      server: "http://www.plantuml.com/plantuml"
plugins:
  - search
