site_name: HomeAssistant documentation
use_directory_urls: False
repo_url: http://homeassistant.local:8000
repo_name: View updates in realtime
theme:
  name: material
  logo: assets/mkdocs_icon.png
  features:
    - header.autohide
  include_search_page: false
  search_index_only: true
extra_css:
  - assets/stylesheet.css
nav:
  - index.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.tilde
  - toc:
      permalink: "#"
  - plantuml_markdown:
      server: "http://www.plantuml.com/plantuml/"
plugins:
  - macros
  - search
