# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-python:3.12-alpine3.20"
  amd64: "ghcr.io/home-assistant/amd64-base-python:3.12-alpine3.20"
  # armhf: "ghcr.io/home-assistant/armhf-base-python:3.12-alpine3.20"
  # armv7: "ghcr.io/home-assistant/armv7-base-python:3.12-alpine3.20"
  # i386: "ghcr.io/home-assistant/i386-base-python:3.12-alpine3.20"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: MkDocs"
  org.opencontainers.image.description: "Create documentation web site in markdown"
  org.opencontainers.image.source: "https://github.com/iXavierBerger/home-assistant-addons"
  org.opencontainers.image.licenses: "MIT"
args:
  TEMPIO_VERSION: "0.0.1"
