name: mkdocs
version: "1.1.2"
slug: mkdocs
image: "ghcr.io/xavierberger/{arch}-addon-mkdocs"
codenotary: "berger.xavier@gmail.com"
description: "Project documentation with Markdown."
init: false
arch:
  - aarch64
  - amd64
ingress: true
panel_icon: mdi:book-open-variant-outline
panel_title: MkDocs
ports:
  8000/tcp: 8000
ports_description:
  8000/tcp: "MkDocs realtime preview"
map:
  - addon_config:rw
