name: mkdocs
description: "Create documentation web site in markdown"
version: "0.0.1"
image: "ghcr.io/xavierberger/{arch}-addon-mkdocs"
slug: mkdocs
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ingress: true
ingress_port: 9000
ingress_stream: true
panel_icon: mdi:book-open-variant-outline
panel_title: MkDocs
ports:
  9000/tcp: # Not needed for ingress
  8000/tcp: 8000
map:
  - addon_config:rw
  - share:rw
