name: mkdocs
version: "0.0.15"
image: "ghcr.io/xavierberger/{arch}-addon-mkdocs"
codenotary: "berger.xavier@gmail.com"
slug: mkdocs
description: "Project documentation with Markdown."
init: false
arch:
  - aarch64
  - amd64
startup: services
ingress: true
ingress_port: 9000
ingress_stream: true
panel_icon: mdi:book-open-variant-outline
panel_title: MkDocs
ports:
  9000/tcp: # Not needed for ingress
  8000/tcp: 8000
map:
  - addon_config:rw
